// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Country struct {
	Hotels []*Hotel `json:"hotels"`
}

type DeleteHotel struct {
	ID string `json:"id"`
}

type Hotel struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type HotelMutation struct {
	CreateHotel  *Hotel   `json:"createHotel"`
	CreateHotels []*Hotel `json:"createHotels"`
	UpdateHotel  *Hotel   `json:"updateHotel"`
	DeleteHotel  *Hotel   `json:"deleteHotel"`
}

type NewHotel struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
