# if you are using colima, do 
# colima start --edit
# ensure you have 
# provision:
#   - mode: system
#     script: sysctl -w vm.max_map_count=262144
# as suggested at https://github.com/abiosoft/colima/issues/384
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    network_mode: host

volumes:
  data01:
    driver: local